package HibernateClasses;
// Generated Nov 4, 2015 1:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Container generated by hbm2java
 */
public class Container  implements java.io.Serializable {


     private Integer idc;
     private ContainerType containerType;
     private User user;
     private Double totalProducts;
     private Double totalAmount;
     private Date date;
     private Set<ProductInContainer> productInContainers = new HashSet<ProductInContainer>(0);
     private Set<Invoice> invoices = new HashSet<Invoice>(0);

    public Container() {
    }

	
    public Container(ContainerType containerType, User user) {
        this.containerType = containerType;
        this.user = user;
    }
    public Container(ContainerType containerType, User user, Double totalProducts, Double totalAmount, Date date, Set<ProductInContainer> productInContainers, Set<Invoice> invoices) {
       this.containerType = containerType;
       this.user = user;
       this.totalProducts = totalProducts;
       this.totalAmount = totalAmount;
       this.date = date;
       this.productInContainers = productInContainers;
       this.invoices = invoices;
    }
   
    public Integer getIdc() {
        return this.idc;
    }
    
    public void setIdc(Integer idc) {
        this.idc = idc;
    }
    public ContainerType getContainerType() {
        return this.containerType;
    }
    
    public void setContainerType(ContainerType containerType) {
        this.containerType = containerType;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public Double getTotalProducts() {
        return this.totalProducts;
    }
    
    public void setTotalProducts(Double totalProducts) {
        this.totalProducts = totalProducts;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Set<ProductInContainer> getProductInContainers() {
        return this.productInContainers;
    }
    
    public void setProductInContainers(Set<ProductInContainer> productInContainers) {
        this.productInContainers = productInContainers;
    }
    public Set<Invoice> getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set<Invoice> invoices) {
        this.invoices = invoices;
    }




}


