package HibernateClasses;
// Generated Nov 4, 2015 1:58:45 PM by Hibernate Tools 4.3.1



/**
 * Description generated by hbm2java
 */
public class Description  implements java.io.Serializable {


     private Integer iddescription;
     private Product product;
     private String general2gNetwork;
     private String general3gNetwork;
     private String general4gNetwork;
     private String generalSim;
     private String generalAnnounced;
     private String generalStatus;
     private String bodyDimensions;
     private String bodyWeight;
     private String displayType;
     private String displaySize;
     private String displayMultitouch;
     private String displayProtection;
     private String soundAlertType;
     private String soundLoudspeaker;
     private String sound35mmJack;
     private String memoryCardSlot;
     private String memoryInternal;
     private String dataGprs;
     private String dataEdge;
     private String dataSpeed;
     private String dataWlan;
     private String dataBluetooth;
     private String dataNfc;
     private String dataInfraredPort;
     private String dataUsb;
     private String cameraPrimary;
     private String cameraFeatures;
     private String cameraVideo;
     private String cameraSecondary;
     private String featuresOs;
     private String featuresChipset;
     private String featuresCpu;
     private String featuresGpu;
     private String featuresSensors;
     private String featuresMessaging;
     private String featuresBrowser;
     private String featuresRadio;
     private String featuresGps;
     private String featuresJava;
     private String featuresColours;
     private String batteryType;
     private String batteryStandby;
     private String batteryTalktime;
     private String batteryMusicPlay;
     private String miscSarUs;
     private String miscSarEu;
     private String testsDisplay;
     private String testsLoudspeaker;
     private String testsAudioQuality;
     private String testsCamera;
     private String testsBatteryLife;

    public Description() {
    }

	
    public Description(Product product) {
        this.product = product;
    }
    public Description(Product product, String general2gNetwork, String general3gNetwork, String general4gNetwork, String generalSim, String generalAnnounced, String generalStatus, String bodyDimensions, String bodyWeight, String displayType, String displaySize, String displayMultitouch, String displayProtection, String soundAlertType, String soundLoudspeaker, String sound35mmJack, String memoryCardSlot, String memoryInternal, String dataGprs, String dataEdge, String dataSpeed, String dataWlan, String dataBluetooth, String dataNfc, String dataInfraredPort, String dataUsb, String cameraPrimary, String cameraFeatures, String cameraVideo, String cameraSecondary, String featuresOs, String featuresChipset, String featuresCpu, String featuresGpu, String featuresSensors, String featuresMessaging, String featuresBrowser, String featuresRadio, String featuresGps, String featuresJava, String featuresColours, String batteryType, String batteryStandby, String batteryTalktime, String batteryMusicPlay, String miscSarUs, String miscSarEu, String testsDisplay, String testsLoudspeaker, String testsAudioQuality, String testsCamera, String testsBatteryLife) {
       this.product = product;
       this.general2gNetwork = general2gNetwork;
       this.general3gNetwork = general3gNetwork;
       this.general4gNetwork = general4gNetwork;
       this.generalSim = generalSim;
       this.generalAnnounced = generalAnnounced;
       this.generalStatus = generalStatus;
       this.bodyDimensions = bodyDimensions;
       this.bodyWeight = bodyWeight;
       this.displayType = displayType;
       this.displaySize = displaySize;
       this.displayMultitouch = displayMultitouch;
       this.displayProtection = displayProtection;
       this.soundAlertType = soundAlertType;
       this.soundLoudspeaker = soundLoudspeaker;
       this.sound35mmJack = sound35mmJack;
       this.memoryCardSlot = memoryCardSlot;
       this.memoryInternal = memoryInternal;
       this.dataGprs = dataGprs;
       this.dataEdge = dataEdge;
       this.dataSpeed = dataSpeed;
       this.dataWlan = dataWlan;
       this.dataBluetooth = dataBluetooth;
       this.dataNfc = dataNfc;
       this.dataInfraredPort = dataInfraredPort;
       this.dataUsb = dataUsb;
       this.cameraPrimary = cameraPrimary;
       this.cameraFeatures = cameraFeatures;
       this.cameraVideo = cameraVideo;
       this.cameraSecondary = cameraSecondary;
       this.featuresOs = featuresOs;
       this.featuresChipset = featuresChipset;
       this.featuresCpu = featuresCpu;
       this.featuresGpu = featuresGpu;
       this.featuresSensors = featuresSensors;
       this.featuresMessaging = featuresMessaging;
       this.featuresBrowser = featuresBrowser;
       this.featuresRadio = featuresRadio;
       this.featuresGps = featuresGps;
       this.featuresJava = featuresJava;
       this.featuresColours = featuresColours;
       this.batteryType = batteryType;
       this.batteryStandby = batteryStandby;
       this.batteryTalktime = batteryTalktime;
       this.batteryMusicPlay = batteryMusicPlay;
       this.miscSarUs = miscSarUs;
       this.miscSarEu = miscSarEu;
       this.testsDisplay = testsDisplay;
       this.testsLoudspeaker = testsLoudspeaker;
       this.testsAudioQuality = testsAudioQuality;
       this.testsCamera = testsCamera;
       this.testsBatteryLife = testsBatteryLife;
    }
   
    public Integer getIddescription() {
        return this.iddescription;
    }
    
    public void setIddescription(Integer iddescription) {
        this.iddescription = iddescription;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getGeneral2gNetwork() {
        return this.general2gNetwork;
    }
    
    public void setGeneral2gNetwork(String general2gNetwork) {
        this.general2gNetwork = general2gNetwork;
    }
    public String getGeneral3gNetwork() {
        return this.general3gNetwork;
    }
    
    public void setGeneral3gNetwork(String general3gNetwork) {
        this.general3gNetwork = general3gNetwork;
    }
    public String getGeneral4gNetwork() {
        return this.general4gNetwork;
    }
    
    public void setGeneral4gNetwork(String general4gNetwork) {
        this.general4gNetwork = general4gNetwork;
    }
    public String getGeneralSim() {
        return this.generalSim;
    }
    
    public void setGeneralSim(String generalSim) {
        this.generalSim = generalSim;
    }
    public String getGeneralAnnounced() {
        return this.generalAnnounced;
    }
    
    public void setGeneralAnnounced(String generalAnnounced) {
        this.generalAnnounced = generalAnnounced;
    }
    public String getGeneralStatus() {
        return this.generalStatus;
    }
    
    public void setGeneralStatus(String generalStatus) {
        this.generalStatus = generalStatus;
    }
    public String getBodyDimensions() {
        return this.bodyDimensions;
    }
    
    public void setBodyDimensions(String bodyDimensions) {
        this.bodyDimensions = bodyDimensions;
    }
    public String getBodyWeight() {
        return this.bodyWeight;
    }
    
    public void setBodyWeight(String bodyWeight) {
        this.bodyWeight = bodyWeight;
    }
    public String getDisplayType() {
        return this.displayType;
    }
    
    public void setDisplayType(String displayType) {
        this.displayType = displayType;
    }
    public String getDisplaySize() {
        return this.displaySize;
    }
    
    public void setDisplaySize(String displaySize) {
        this.displaySize = displaySize;
    }
    public String getDisplayMultitouch() {
        return this.displayMultitouch;
    }
    
    public void setDisplayMultitouch(String displayMultitouch) {
        this.displayMultitouch = displayMultitouch;
    }
    public String getDisplayProtection() {
        return this.displayProtection;
    }
    
    public void setDisplayProtection(String displayProtection) {
        this.displayProtection = displayProtection;
    }
    public String getSoundAlertType() {
        return this.soundAlertType;
    }
    
    public void setSoundAlertType(String soundAlertType) {
        this.soundAlertType = soundAlertType;
    }
    public String getSoundLoudspeaker() {
        return this.soundLoudspeaker;
    }
    
    public void setSoundLoudspeaker(String soundLoudspeaker) {
        this.soundLoudspeaker = soundLoudspeaker;
    }
    public String getSound35mmJack() {
        return this.sound35mmJack;
    }
    
    public void setSound35mmJack(String sound35mmJack) {
        this.sound35mmJack = sound35mmJack;
    }
    public String getMemoryCardSlot() {
        return this.memoryCardSlot;
    }
    
    public void setMemoryCardSlot(String memoryCardSlot) {
        this.memoryCardSlot = memoryCardSlot;
    }
    public String getMemoryInternal() {
        return this.memoryInternal;
    }
    
    public void setMemoryInternal(String memoryInternal) {
        this.memoryInternal = memoryInternal;
    }
    public String getDataGprs() {
        return this.dataGprs;
    }
    
    public void setDataGprs(String dataGprs) {
        this.dataGprs = dataGprs;
    }
    public String getDataEdge() {
        return this.dataEdge;
    }
    
    public void setDataEdge(String dataEdge) {
        this.dataEdge = dataEdge;
    }
    public String getDataSpeed() {
        return this.dataSpeed;
    }
    
    public void setDataSpeed(String dataSpeed) {
        this.dataSpeed = dataSpeed;
    }
    public String getDataWlan() {
        return this.dataWlan;
    }
    
    public void setDataWlan(String dataWlan) {
        this.dataWlan = dataWlan;
    }
    public String getDataBluetooth() {
        return this.dataBluetooth;
    }
    
    public void setDataBluetooth(String dataBluetooth) {
        this.dataBluetooth = dataBluetooth;
    }
    public String getDataNfc() {
        return this.dataNfc;
    }
    
    public void setDataNfc(String dataNfc) {
        this.dataNfc = dataNfc;
    }
    public String getDataInfraredPort() {
        return this.dataInfraredPort;
    }
    
    public void setDataInfraredPort(String dataInfraredPort) {
        this.dataInfraredPort = dataInfraredPort;
    }
    public String getDataUsb() {
        return this.dataUsb;
    }
    
    public void setDataUsb(String dataUsb) {
        this.dataUsb = dataUsb;
    }
    public String getCameraPrimary() {
        return this.cameraPrimary;
    }
    
    public void setCameraPrimary(String cameraPrimary) {
        this.cameraPrimary = cameraPrimary;
    }
    public String getCameraFeatures() {
        return this.cameraFeatures;
    }
    
    public void setCameraFeatures(String cameraFeatures) {
        this.cameraFeatures = cameraFeatures;
    }
    public String getCameraVideo() {
        return this.cameraVideo;
    }
    
    public void setCameraVideo(String cameraVideo) {
        this.cameraVideo = cameraVideo;
    }
    public String getCameraSecondary() {
        return this.cameraSecondary;
    }
    
    public void setCameraSecondary(String cameraSecondary) {
        this.cameraSecondary = cameraSecondary;
    }
    public String getFeaturesOs() {
        return this.featuresOs;
    }
    
    public void setFeaturesOs(String featuresOs) {
        this.featuresOs = featuresOs;
    }
    public String getFeaturesChipset() {
        return this.featuresChipset;
    }
    
    public void setFeaturesChipset(String featuresChipset) {
        this.featuresChipset = featuresChipset;
    }
    public String getFeaturesCpu() {
        return this.featuresCpu;
    }
    
    public void setFeaturesCpu(String featuresCpu) {
        this.featuresCpu = featuresCpu;
    }
    public String getFeaturesGpu() {
        return this.featuresGpu;
    }
    
    public void setFeaturesGpu(String featuresGpu) {
        this.featuresGpu = featuresGpu;
    }
    public String getFeaturesSensors() {
        return this.featuresSensors;
    }
    
    public void setFeaturesSensors(String featuresSensors) {
        this.featuresSensors = featuresSensors;
    }
    public String getFeaturesMessaging() {
        return this.featuresMessaging;
    }
    
    public void setFeaturesMessaging(String featuresMessaging) {
        this.featuresMessaging = featuresMessaging;
    }
    public String getFeaturesBrowser() {
        return this.featuresBrowser;
    }
    
    public void setFeaturesBrowser(String featuresBrowser) {
        this.featuresBrowser = featuresBrowser;
    }
    public String getFeaturesRadio() {
        return this.featuresRadio;
    }
    
    public void setFeaturesRadio(String featuresRadio) {
        this.featuresRadio = featuresRadio;
    }
    public String getFeaturesGps() {
        return this.featuresGps;
    }
    
    public void setFeaturesGps(String featuresGps) {
        this.featuresGps = featuresGps;
    }
    public String getFeaturesJava() {
        return this.featuresJava;
    }
    
    public void setFeaturesJava(String featuresJava) {
        this.featuresJava = featuresJava;
    }
    public String getFeaturesColours() {
        return this.featuresColours;
    }
    
    public void setFeaturesColours(String featuresColours) {
        this.featuresColours = featuresColours;
    }
    public String getBatteryType() {
        return this.batteryType;
    }
    
    public void setBatteryType(String batteryType) {
        this.batteryType = batteryType;
    }
    public String getBatteryStandby() {
        return this.batteryStandby;
    }
    
    public void setBatteryStandby(String batteryStandby) {
        this.batteryStandby = batteryStandby;
    }
    public String getBatteryTalktime() {
        return this.batteryTalktime;
    }
    
    public void setBatteryTalktime(String batteryTalktime) {
        this.batteryTalktime = batteryTalktime;
    }
    public String getBatteryMusicPlay() {
        return this.batteryMusicPlay;
    }
    
    public void setBatteryMusicPlay(String batteryMusicPlay) {
        this.batteryMusicPlay = batteryMusicPlay;
    }
    public String getMiscSarUs() {
        return this.miscSarUs;
    }
    
    public void setMiscSarUs(String miscSarUs) {
        this.miscSarUs = miscSarUs;
    }
    public String getMiscSarEu() {
        return this.miscSarEu;
    }
    
    public void setMiscSarEu(String miscSarEu) {
        this.miscSarEu = miscSarEu;
    }
    public String getTestsDisplay() {
        return this.testsDisplay;
    }
    
    public void setTestsDisplay(String testsDisplay) {
        this.testsDisplay = testsDisplay;
    }
    public String getTestsLoudspeaker() {
        return this.testsLoudspeaker;
    }
    
    public void setTestsLoudspeaker(String testsLoudspeaker) {
        this.testsLoudspeaker = testsLoudspeaker;
    }
    public String getTestsAudioQuality() {
        return this.testsAudioQuality;
    }
    
    public void setTestsAudioQuality(String testsAudioQuality) {
        this.testsAudioQuality = testsAudioQuality;
    }
    public String getTestsCamera() {
        return this.testsCamera;
    }
    
    public void setTestsCamera(String testsCamera) {
        this.testsCamera = testsCamera;
    }
    public String getTestsBatteryLife() {
        return this.testsBatteryLife;
    }
    
    public void setTestsBatteryLife(String testsBatteryLife) {
        this.testsBatteryLife = testsBatteryLife;
    }




}


