package HibernateClasses;
// Generated Nov 4, 2015 1:58:45 PM by Hibernate Tools 4.3.1



/**
 * Images generated by hbm2java
 */
public class Images  implements java.io.Serializable {


     private Integer idimages;
     private Product product;
     private String imageName;
     private String imagePath;

    public Images() {
    }

	
    public Images(Product product) {
        this.product = product;
    }
    public Images(Product product, String imageName, String imagePath) {
       this.product = product;
       this.imageName = imageName;
       this.imagePath = imagePath;
    }
   
    public Integer getIdimages() {
        return this.idimages;
    }
    
    public void setIdimages(Integer idimages) {
        this.idimages = idimages;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public String getImageName() {
        return this.imageName;
    }
    
    public void setImageName(String imageName) {
        this.imageName = imageName;
    }
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }




}


