package HibernateClasses;
// Generated Nov 4, 2015 1:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idinvoice;
     private Container container;
     private Double invoiceTotal;
     private Date date;

    public Invoice() {
    }

	
    public Invoice(Container container) {
        this.container = container;
    }
    public Invoice(Container container, Double invoiceTotal, Date date) {
       this.container = container;
       this.invoiceTotal = invoiceTotal;
       this.date = date;
    }
   
    public Integer getIdinvoice() {
        return this.idinvoice;
    }
    
    public void setIdinvoice(Integer idinvoice) {
        this.idinvoice = idinvoice;
    }
    public Container getContainer() {
        return this.container;
    }
    
    public void setContainer(Container container) {
        this.container = container;
    }
    public Double getInvoiceTotal() {
        return this.invoiceTotal;
    }
    
    public void setInvoiceTotal(Double invoiceTotal) {
        this.invoiceTotal = invoiceTotal;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


