package HibernateClasses;
// Generated Nov 4, 2015 1:58:45 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * ProductInContainer generated by hbm2java
 */
public class ProductInContainer  implements java.io.Serializable {


     private Integer pcId;
     private Container container;
     private Product product;
     private SystemStatus systemStatus;
     private Double qty;
     private Double amount;
     private Date addedDate;

    public ProductInContainer() {
    }

	
    public ProductInContainer(Container container, Product product, SystemStatus systemStatus) {
        this.container = container;
        this.product = product;
        this.systemStatus = systemStatus;
    }
    public ProductInContainer(Container container, Product product, SystemStatus systemStatus, Double qty, Double amount, Date addedDate) {
       this.container = container;
       this.product = product;
       this.systemStatus = systemStatus;
       this.qty = qty;
       this.amount = amount;
       this.addedDate = addedDate;
    }
   
    public Integer getPcId() {
        return this.pcId;
    }
    
    public void setPcId(Integer pcId) {
        this.pcId = pcId;
    }
    public Container getContainer() {
        return this.container;
    }
    
    public void setContainer(Container container) {
        this.container = container;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public SystemStatus getSystemStatus() {
        return this.systemStatus;
    }
    
    public void setSystemStatus(SystemStatus systemStatus) {
        this.systemStatus = systemStatus;
    }
    public Double getQty() {
        return this.qty;
    }
    
    public void setQty(Double qty) {
        this.qty = qty;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Date getAddedDate() {
        return this.addedDate;
    }
    
    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }




}


