package HibernateClasses;
// Generated Nov 4, 2015 1:58:45 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idproduct;
     private Category category;
     private Make make;
     private String name;
     private String generalDescription;
     private Double availableQty;
     private Double specialPrice;
     private Double customerPrice;
     private String imagePath;
     private String status;
     private Set<Images> imageses = new HashSet<Images>(0);
     private Set<Description> descriptions = new HashSet<Description>(0);
     private Set<Stock> stocks = new HashSet<Stock>(0);
     private Set<ProductInContainer> productInContainers = new HashSet<ProductInContainer>(0);

    public Product() {
    }

	
    public Product(Category category, Make make) {
        this.category = category;
        this.make = make;
    }
    public Product(Category category, Make make, String name, String generalDescription, Double availableQty, Double specialPrice, Double customerPrice, String imagePath, String status, Set<Images> imageses, Set<Description> descriptions, Set<Stock> stocks, Set<ProductInContainer> productInContainers) {
       this.category = category;
       this.make = make;
       this.name = name;
       this.generalDescription = generalDescription;
       this.availableQty = availableQty;
       this.specialPrice = specialPrice;
       this.customerPrice = customerPrice;
       this.imagePath = imagePath;
       this.status = status;
       this.imageses = imageses;
       this.descriptions = descriptions;
       this.stocks = stocks;
       this.productInContainers = productInContainers;
    }
   
    public Integer getIdproduct() {
        return this.idproduct;
    }
    
    public void setIdproduct(Integer idproduct) {
        this.idproduct = idproduct;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Make getMake() {
        return this.make;
    }
    
    public void setMake(Make make) {
        this.make = make;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getGeneralDescription() {
        return this.generalDescription;
    }
    
    public void setGeneralDescription(String generalDescription) {
        this.generalDescription = generalDescription;
    }
    public Double getAvailableQty() {
        return this.availableQty;
    }
    
    public void setAvailableQty(Double availableQty) {
        this.availableQty = availableQty;
    }
    public Double getSpecialPrice() {
        return this.specialPrice;
    }
    
    public void setSpecialPrice(Double specialPrice) {
        this.specialPrice = specialPrice;
    }
    public Double getCustomerPrice() {
        return this.customerPrice;
    }
    
    public void setCustomerPrice(Double customerPrice) {
        this.customerPrice = customerPrice;
    }
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public Set<Images> getImageses() {
        return this.imageses;
    }
    
    public void setImageses(Set<Images> imageses) {
        this.imageses = imageses;
    }
    public Set<Description> getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(Set<Description> descriptions) {
        this.descriptions = descriptions;
    }
    public Set<Stock> getStocks() {
        return this.stocks;
    }
    
    public void setStocks(Set<Stock> stocks) {
        this.stocks = stocks;
    }
    public Set<ProductInContainer> getProductInContainers() {
        return this.productInContainers;
    }
    
    public void setProductInContainers(Set<ProductInContainer> productInContainers) {
        this.productInContainers = productInContainers;
    }




}


